name: CDK Deploy
description: Deploys CDK to an AWS account
inputs:
  deploy_account_id:
    type: string
    description: 'AWS Account from where CI/CD deployments are initiated from'
    required: false
    default: "055117415094"
  target_account_id:
    type: string
    description: 'AWS Account into which the stack will be deployed'
    required: true
  cdk_stack:
    description: 'Stack Name of the CDK app'
    required: true
  artifact_id:
    description: 'Cache key of the pre-built artifacts'
    required: true
  artifact_download_path:
    description: 'Path to download the artifacts'
    required: false
    default: ""
  build_script:
    description: any prebuild commands to run
    required: false
    type: string
    default: echo "No build commands provided."
runs:
  using: composite
  steps:
    - name: Download Artifacts
      uses: actions/cache@v3
      with:
        path: ${{ inputs.artifact_download_path }}
        key: ${{ inputs.artifact_id }}
    - name: Setup CDK Binary
      run: npm install -g aws-cdk
      shell: bash
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ inputs.deploy_account_id }}:role/eonsos-controltower-githubpipeline
    - name: Deploy CDK Stack
      run: ${{ inputs.build_script }} && cdk deploy ${{ inputs.cdk_stack }} --require-approval never
      shell: bash
      working-directory: ${{ inputs.artifact_download_path }}
      env:
        ACCOUNT_ID: ${{ inputs.target_account_id }}
    # - id: date
    #   run: echo "##[set-output name=data;]$(data)"
    #   shell: bash      
    # - name: Deployment Badge - Date
    #   uses: RubbaBoy/BYOB@v1.3.0
    #   with:
    #     NAME: ${{ inputs.cdk_stack }}
    #     LABEL: 'Last deployed at'
    #     STATUS: ${{ steps.date.outputs.data }}
    #     COLOR: 00EEFF
    # - name: Deployment Badge - Date
    #   uses: RubbaBoy/BYOB@v1.3.0
    #   with:
    #     NAME: ${{ inputs.cdk_stack }}-time
    #     LABEL: '${{ inputs.cdk_stack }}: Last deployed:'
    #     STATUS: ${{ steps.date.outputs.data }}
    #     COLOR: 3358FF
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Deployment Badge - SHA
    #   uses: RubbaBoy/BYOB@v1.3.0
    #   with:
    #     NAME: ${{ inputs.cdk_stack }}-sha
    #     LABEL: '${{ inputs.cdk_stack }}: SHA:'
    #     STATUS: ${{ github.sha }}
    #     COLOR: 1EAC0F
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}