on:
  workflow_call:
    inputs:
      # dev_accountid:
      #   required: true
      #   type: string
      # prod_accountid:
      #   required: true
      #   type: string
      cdk_appname:
        required: true
        type: string
      working_dir:
        required: false
        type: string
        default: "."
      dev_build_script:
        required: false
        type: string
        default: echo "No build commands provided."
      prod_build_script:
        required: false
        type: string
        default: echo "No build commands provided."
env:
  ARTIFACT_ID: eon_artifact_${{github.run_id}}
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}      
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: Store Artifacts
        uses: actions/cache@v3
        with:
          path: ${{ inputs.working_dir }}
          key: ${{env.ARTIFACT_ID}}
  DeployToDev:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: eonsos/eonsos-common/.github/actions/cdk-deploy@main
        with:
          deploy_account_id: "055117415094"
          cdk_stack: ${{ inputs.cdk_appname }}-dev
          artifact_id: ${{env.ARTIFACT_ID}}
          artifact_download_path: ${{ inputs.working_dir }}
          build_script: ${{ inputs.dev_build_script }}